### ISSUE TITLE
*journalmanager.tasks.link_article_to_issue* não trata artigos vinculados a números suplementares e especiais.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1248]
A *task* deve identificar a ocorrência das substrings **suppl** e **spe** no conteúdo do elemento ``/article/front/article-meta/issue``, e considerar os valor dos atributos **Issue.suppl_text** e **Issue.special_text**, respectivamente. E.g.: ``36 (4 suppl.0)`` deve ser traduzido para uma consulta parecida com **{'volume': '36', 'number': '4', 'suppl_text': '0'}**

Exceção que está sendo levantada atualmente:
```
Task journalmanager.tasks.link_article_to_issue with id b0a0047f-ee24-424a-beac-f7ab25773295 raised exception:
'MultipleObjectsReturned("get() returned more than one Issue -- it returned 2! Lookup parameters were {\'volume\': \'36\', \'number\': \'4\', \'publication_year\': \'2002\'}",)'


Task was called with args: (53238,) kwargs: {}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/var/www/.virtualenvs/scielomanager/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/.virtualenvs/scielomanager/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/manager_scielo_org/scielomanager/journalmanager/tasks.py", line 184, in link_article_to_issue
    volume=volume, number=issue, publication_year=year)
  File "/var/www/.virtualenvs/scielomanager/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/var/www/.virtualenvs/scielomanager/lib/python2.7/site-packages/django/db/models/query.py", line 368, in get
    % (self.model._meta.object_name, num, kwargs))
MultipleObjectsReturned: get() returned more than one Issue -- it returned 2! Lookup parameters were {'volume': '36', 'number': '4', 'publication_year': '2002'}
```

**Comment by gustavofonseca** [comment]
O pull request #1250 é um _work around_ que evita os erros, mas não resolve o problema.

**Comment by lpanebr** [comment]
será que ao invés de simplificar o scielo manager terão que complicar o SPS usando `<supplement>`?[1]

```xml
...
<article-meta>
...
<volume>52</volume>
<issue>1</issue>
<supplement>1</supplement>
<fpage>437</fpage>
<lpage>467</lpage>
...
</article-meta>
...
```

[1] http://jats.nlm.nih.gov/publishing/tag-library/1.1d1/n-xnd0.html

**Comment by gustavofonseca** [comment]
@lpanebr, está falando sobre o ticket #1249? Se sim, estamos discutindo internamente sobre considerar o elemento ``<supplement>`` e algum outro para denotar números especiais, e assim reduzir essa carga semântica do elemento ``<issue>``. Mas trata-se de outro ticket rs.

**Comment by lpanebr** [comment]
Sim. Vou comentar lá.
