### ISSUE TITLE
celery.exceptions.ImproperlyConfigured: Celery 4.x requires Django 1.8 or later

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/scielo-manager#1362]
Erro acontece durante a execução dos testes automatizados pelo Travis. Veja mais: https://travis-ci.org/scieloorg/scielo-manager/builds/178067487.
```
Traceback (most recent call last):

  File "scielomanager/manage.py", line 9, in <module>

    execute_from_command_line(sys.argv)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line

    utility.execute()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 252, in fetch_command

    app_name = get_commands()[subcommand]

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 101, in get_commands

    apps = settings.INSTALLED_APPS

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner

    self._setup()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup

    self._wrapped = Settings(settings_module)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 93, in __init__

    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module

    __import__(name)

  File "/home/travis/build/scieloorg/scielo-manager/scielomanager/scielomanager/__init__.py", line 5, in <module>

    from .celery import app as celery_app

  File "/home/travis/build/scieloorg/scielo-manager/scielomanager/scielomanager/celery.py", line 13, in <module>

    app = Celery('scielomanager', broker='django://')

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/celery/app/base.py", line 288, in __init__

    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/celery/fixups/django.py", line 48, in fixup

    _verify_django_version(django)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/celery/fixups/django.py", line 36, in _verify_django_version

    raise ImproperlyConfigured('Celery 4.x requires Django 1.8 or later.')

celery.exceptions.ImproperlyConfigured: Celery 4.x requires Django 1.8 or later.
```

**Comment by iver3on** [comment]
I found this bug too.no body else resolve it?

**Comment by iluks** [comment]
I have a similar issue with Katello foreman 1.17.4 on RedHat RHEL 7.7 and 7.4
django.py:34:_verify_django_version:ImproperlyConfigured: Celery 4.x requires Django 1.8 or later.

Traceback (most recent call last):
  File "/usr/bin/celery", line 9, in <module>
    load_entry_point('celery==4.2.1', 'console_scripts', 'celery')()
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 501, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/usr/lib/python2.7/site-packages/celery/app/utils.py", line 362, in find_app
    sym = imp(app)
  File "/usr/lib/python2.7/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/pulp/server/async/app.py", line 18, in <module>
    from pulp.server.async import tasks, worker_watcher
  File "/usr/lib/python2.7/site-packages/pulp/server/async/tasks.py", line 22, in <module>
    from pulp.server.async.celery_instance import celery, RESOURCE_MANAGER_QUEUE, \
  File "/usr/lib/python2.7/site-packages/pulp/server/async/celery_instance.py", line 20, in <module>
    celery = Celery('tasks', broker=broker_url)
  File "/usr/lib/python2.7/site-packages/celery/app/base.py", line 281, in __init__
    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]
  File "/usr/lib/python2.7/site-packages/celery/fixups/django.py", line 46, in fixup
    _verify_django_version(django)
  File "/usr/lib/python2.7/site-packages/celery/fixups/django.py", line 34, in _verify_django_version
    raise ImproperlyConfigured('Celery 4.x requires Django 1.8 or later.')
ImproperlyConfigured: Celery 4.x requires Django 1.8 or later.

**Comment by cprmrj** [comment]
Any solution ?
